#!/usr/bin/env Rscript
# Automatically generated by provisionr
{
    args <- commandArgs(trailingOnly = FALSE)
    file <- grep("^--file=", args, value = TRUE)
    if (length(file) != 1L) {
        stop("Could not determine path to running script")
    }
    here <- dirname(normalizePath(sub("^--file=", "", file)))
    message(sprintf("Working in '%s'", here))
    setwd(here)
    dir.create(".packages", FALSE)
    if (TRUE) {
        .libPaths(".packages")
    }
    else {
        .libPaths(c(".packages", .libPaths()))
    }
    repos <- c("https://cran.rstudio.com", "https://mrc-ide.github.io/drat/")
    has_provisionr <- function() {
        requireNamespace("provisionr", quietly = TRUE, lib.loc = if (TRUE)
            ".packages"
        else NULL)
    }
    if (!has_provisionr()) {
        message("Installing provisionr")
        install.packages("provisionr", repos = repos, lib = ".packages")
    }
    if (!has_provisionr()) {
        stop("Failed to bootstrap provisionr")
    }
    src <- provisionr::package_sources(data = NULL)
    provisionr::provision_dependencies(".packages", src = src,
        read_travis = TRUE)
    if (!file.exists(".Renviron")) {
        writeLines(sprintf("R_LIBS_USER=\"%s\"", ".packages"),
            ".Renviron")
    }
}
