#!/usr/bin/env Rscript
"Usage:
  rrq_test [--source=SOURCE...] [--package=PACKAGE...] [options] <expr>

Options:
  --workers=N   Number of workers to launch [default: 0]
  --dest=FILE   Destination to write output to [default: rrq_data]
  --root=ROOT   Context root directory [default: context]" -> usage
opts <- docopt::docopt(usage)
expr <- parse(text = opts$expr)[[1L]]

rrq:::rrq_test(expr, sources = opts$source, packages = opts$package,
               n_workers = as.integer(opts$workers),
               dest = opts$dest, root = opts$root)
