#!/usr/bin/env Rscript
dir.create("inst/banner", FALSE, TRUE)
## rstrip(strsplit(as.character(fig), "\n")[[1]])
writeLines(
  as.character(rfiglet::figlet(sprintf("_- %s -_", "rrq!"), "slant")),
           "inst/banner/start")
writeLines(
  as.character(rfiglet::figlet(sprintf("bye bye for now"), "smslant")),
  "inst/banner/stop")
